/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import form.*;
import controller.Controller;
import domain.Administrator;
import domain.Knjiga;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import model.TabelaKnjige;

/**
 *
 * @author Maja
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    Administrator admin;
    public FrmMain() {
        initComponents();
//        this.admin=admin;
//        setTitle("Welcome "+admin.getKorisnickoIme());
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcomeMessage = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuClanoviBiblioteke = new javax.swing.JMenu();
        menuItemViewAllClanovi = new javax.swing.JMenuItem();
        menuItemAddClan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItemViewAllKnjiga = new javax.swing.JMenuItem();
        menuItemAddKnjiga = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemViewAllPrimerci = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuItemKreirajPozajmicu = new javax.swing.JMenuItem();
        menuItemIzbrisiPozajmicu = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuItemViewAllRecenzije = new javax.swing.JMenuItem();
        menuItemAddRecenzija = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcomeMessage.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblWelcomeMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcomeMessage.setText("jLabel2");
        getContentPane().add(lblWelcomeMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 290, 70));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/biblioteka.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 260));

        menuClanoviBiblioteke.setText("Clanovi biblioteke");

        menuItemViewAllClanovi.setText("View all");
        menuItemViewAllClanovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemViewAllClanoviActionPerformed(evt);
            }
        });
        menuClanoviBiblioteke.add(menuItemViewAllClanovi);

        menuItemAddClan.setText("Add");
        menuClanoviBiblioteke.add(menuItemAddClan);

        jMenuBar1.add(menuClanoviBiblioteke);

        jMenu3.setText("Knjige");

        menuItemViewAllKnjiga.setText(" View all");
        jMenu3.add(menuItemViewAllKnjiga);

        menuItemAddKnjiga.setText("Add");
        jMenu3.add(menuItemAddKnjiga);

        jMenuBar1.add(jMenu3);

        jMenu2.setText(" Primerci");

        menuItemViewAllPrimerci.setText("View all");
        jMenu2.add(menuItemViewAllPrimerci);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Iznajmljivanje");

        menuItemKreirajPozajmicu.setText(" Kreiraj pozajmicu");
        jMenu4.add(menuItemKreirajPozajmicu);

        menuItemIzbrisiPozajmicu.setText("Izbrisi pozajmicu");
        jMenu4.add(menuItemIzbrisiPozajmicu);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Recenzije");

        menuItemViewAllRecenzije.setText("View all");
        jMenu5.add(menuItemViewAllRecenzije);

        menuItemAddRecenzija.setText("Add");
        jMenu5.add(menuItemAddRecenzija);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void menuItemViewAllClanoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemViewAllClanoviActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemViewAllClanoviActionPerformed

    public Administrator getAdmin() {
        return admin;
    }

    public void setAdmin(Administrator admin) {
        this.admin = admin;
    }




    public JMenuItem getMenuItemAddKnjiga() {
        return menuItemAddKnjiga;
    }

    public void setMenuItemAddKnjiga(JMenuItem menuItemAddKnjiga) {
        this.menuItemAddKnjiga = menuItemAddKnjiga;
    }

    public JMenuItem getMenuItemViewAllKnjiga() {
        return menuItemViewAllKnjiga;
    }

    public void setMenuItemViewAllKnjiga(JMenuItem menuItemViewAllKnjiga) {
        this.menuItemViewAllKnjiga = menuItemViewAllKnjiga;
    }


    

    public JButton getBtnLogout() {
        return btnLogout;
    }

    public void setBtnLogout(JButton btnLogout) {
        this.btnLogout = btnLogout;
    }

    public JMenuItem getMenuItemAddRecenzija() {
        return menuItemAddRecenzija;
    }

    public JMenuItem getMenuItemViewAllRecenzije() {
        return menuItemViewAllRecenzije;
    }


    





    public JMenu getMenuClanoviBiblioteke() {
        return menuClanoviBiblioteke;
    }

    public void setMenuClanoviBiblioteke(JMenu menuClanoviBiblioteke) {
        this.menuClanoviBiblioteke = menuClanoviBiblioteke;
    }

    public JMenuItem getMenuItemAddClan() {
        return menuItemAddClan;
    }

    public void setMenuItemAddClan(JMenuItem menuItemAddClan) {
        this.menuItemAddClan = menuItemAddClan;
    }

    public JMenuItem getMenuItemViewAllClanovi() {
        return menuItemViewAllClanovi;
    }

    public void setMenuItemViewAllClanovi(JMenuItem menuItemViewAllClanovi) {
        this.menuItemViewAllClanovi = menuItemViewAllClanovi;
    }

    public JMenuItem getMenuItemViewAllPrimerci() {
        return menuItemViewAllPrimerci;
    }
    
    public JMenuItem getMenuItemIzbrisiPozajmicu() {
        return menuItemIzbrisiPozajmicu;
    }

    public JMenuItem getMenuItemKreirajPozajmicu() {
        return menuItemKreirajPozajmicu;
    }

    
    public void btnLogoutbtnAddActionListener(ActionListener actionListener) {
        btnLogout.addActionListener(actionListener);
    }     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblWelcomeMessage;
    private javax.swing.JMenu menuClanoviBiblioteke;
    private javax.swing.JMenuItem menuItemAddClan;
    private javax.swing.JMenuItem menuItemAddKnjiga;
    private javax.swing.JMenuItem menuItemAddRecenzija;
    private javax.swing.JMenuItem menuItemIzbrisiPozajmicu;
    private javax.swing.JMenuItem menuItemKreirajPozajmicu;
    private javax.swing.JMenuItem menuItemViewAllClanovi;
    private javax.swing.JMenuItem menuItemViewAllKnjiga;
    private javax.swing.JMenuItem menuItemViewAllPrimerci;
    private javax.swing.JMenuItem menuItemViewAllRecenzije;
    // End of variables declaration//GEN-END:variables

    public JLabel getLblWelcomeMessage() {
        return lblWelcomeMessage;
    }

    public void setLblWelcomeMessage(JLabel lblWelcomeMessage) {
        this.lblWelcomeMessage = lblWelcomeMessage;
    }


}
